name: PR Checks

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v7

      - name: 🏗 Setup Node
        uses: actions/setup-node@v6
        with:
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: 📦 Install dependencies
        run: yarn install

      - name: 🔬 Lint
        run: yarn lint

      - name: 🧼 Format
        run: yarn prettier . --check

      - name: 🧪 Test
        run: yarn test

      - name: 🧱 Compile Expo Plugins
        run: ./scripts/compile-plugins.sh

      - name: 📝 Typescript
        run: yarn tsc --noEmit

      - name: 🍎 iOS Build
        run: yarn expo export -p ios
