name: PR Checks

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v7

      - name: 🏗 Setup Node
        uses: actions/setup-node@v6
        with:
          cache: npm
          cache-dependency-path: package-lock.json

      - name: 📦 Install dependencies
        run: npm install

      - name: 🔬 Lint
        run: npm run lint

      - name: 🧼 Format
        run: npx prettier . --check

      - name: 🧪 Test
        run: npm run test

      - name: 📝 Typescript
        run: npx tsc --noEmit

      - name: 🧱 Compile Expo Plugins
        run: ./scripts/compile-plugins.sh

      - name: 🍎 iOS Build
        run: npx expo export -p ios
